export const HOME_V2_COPY = {
  es: {
    navMinigames: "Minijuegos",
    navCards: "Base de datos",
    navCollection: "Colección",
    infoLabel: "Información",
    heroKicker: "Retos diarios de Hearthstone",
    heroTitle: "Hearthdle",
    heroSubtitle: "Minijuegos diarios de cartas de Hearthstone.",
    resetPrefix: "Nuevos retos en",
    loading: "Cargando cartas...",
    sectionTitle: "Selecciona un modo",
    sectionSubtitle: "Juega el reto del día, consulta cartas o prepara tu colección.",
    footerTip: "Los modos activos usarán retos diarios. La colección llegará más adelante.",
    play: "Jugar",
    open: "Abrir",
    soon: "Próximamente",
    daily: "Diario",
    available: "Disponible",
  },
  en: {
    navMinigames: "Minigames",
    navCards: "Card database",
    navCollection: "Collection",
    infoLabel: "Information",
    heroKicker: "Daily Hearthstone challenges",
    heroTitle: "Hearthdle",
    heroSubtitle: "Daily Hearthstone card minigames.",
    resetPrefix: "New challenges in",
    loading: "Loading cards...",
    sectionTitle: "Choose a mode",
    sectionSubtitle: "Play today’s challenge, browse cards, or prepare your collection.",
    footerTip: "Active modes will use daily challenges. Collection support is coming later.",
    play: "Play",
    open: "Open",
    soon: "Coming soon",
    daily: "Daily",
    available: "Available",
  },
};

export const HOME_V2_MODES = [
  {
    id: "guessMana",
    route: "/guess-mana",
    icon: "✦",
    accent: "blue",
    kind: "daily",
    es: {
      title: "Adivina el coste",
      description: "Observa la carta y elige su coste real.",
      cta: "play",
    },
    en: {
      title: "Guess the Cost",
      description: "Look at the card and choose its real mana cost.",
      cta: "play",
    },
  },
  {
    id: "impostor",
    route: "/impostor",
    icon: "◈",
    accent: "violet",
    kind: "daily",
    es: {
      title: "Encuentra el impostor",
      description: "Detecta qué cartas encajan y evita la trampa.",
      cta: "play",
    },
    en: {
      title: "Find the Impostor",
      description: "Spot the cards that fit and avoid the trap.",
      cta: "play",
    },
  },
  {
    id: "cardArt",
    route: null,
    icon: "◌",
    accent: "cyan",
    kind: "soon",
    es: {
      title: "Card Art",
      description: "Adivina la carta por una parte de su ilustración.",
      cta: "soon",
    },
    en: {
      title: "Card Art",
      description: "Guess the card from a cropped piece of its artwork.",
      cta: "soon",
    },
  },
  {
    id: "grid",
    route: "/grid",
    icon: "▦",
    accent: "gold",
    kind: "daily",
    es: {
      title: "Grid de cartas",
      description: "Completa la cuadrícula con cartas que cumplan fila y columna.",
      cta: "play",
    },
    en: {
      title: "Card Grid",
      description: "Complete the grid with cards matching each row and column.",
      cta: "play",
    },
  },
  {
    id: "cards",
    route: "/cards",
    icon: "⌕",
    accent: "emerald",
    kind: "available",
    es: {
      title: "Base de datos",
      description: "Explora, filtra y consulta todas las cartas.",
      cta: "open",
    },
    en: {
      title: "Card Database",
      description: "Browse, filter, and inspect every card.",
      cta: "open",
    },
  },
  {
    id: "collection",
    route: null,
    icon: "⬡",
    accent: "muted",
    kind: "soon",
    es: {
      title: "Colección",
      description: "Guarda tus cartas y sigue tu progreso.",
      cta: "soon",
    },
    en: {
      title: "Collection",
      description: "Save your cards and track your progress.",
      cta: "soon",
    },
  },
];
