export const HOME_V3_COPY = {
  es: {
    navMinigames: "Minijuegos",
    navCards: "Base de datos",
    navCollection: "Colección",
    infoLabel: "Información",
    profileLabel: "Perfil",
    resetPrefix: "Nuevos retos en",
    loading: "Cargando cartas...",
    gamesTitle: "Retos de la Taberna",
    libraryTitle: "Cofres y Colección",
    play: "Jugar",
    open: "Abrir",
    soon: "Próximamente",
    daily: "Diario",
    available: "Disponible",
    packLabel: "Cofres",
    progressTitle: "Progreso Diario",
    collectionProgress: "Colección",
    completedShort: "Completado",
    pendingShort: "Pendiente",
    dailyWon: "¡Completado!",
    dailyLost: "¡Fallado!",
    dailyPending: "Pendiente",
  },
  en: {
    navMinigames: "Minigames",
    navCards: "Card Database",
    navCollection: "Collection",
    infoLabel: "Information",
    profileLabel: "Profile",
    brandLabel: "Hearthdle",
    themeTavern: "Enable Tavern Mode",
    themeArcane: "Enable Arcane Mode",
    themeTavernActive: "Tavern Mode Active",
    themeArcaneActive: "Arcane Mode Active",
    resetPrefix: "New challenges in",
    loading: "Loading cards...",
    gamesTitle: "Tavern Challenges",
    libraryTitle: "Chests & Collection",
    play: "Play",
    open: "Open",
    soon: "Coming soon",
    daily: "Daily",
    available: "Available",
    packLabel: "Chests",
    progressTitle: "Daily Progress",
    collectionProgress: "Collection",
    completedShort: "Done",
    pendingShort: "Pending",
    dailyWon: "Completed!",
    dailyLost: "Failed!",
    dailyPending: "Pending",
  },
};

export const HOME_V3_MODES = [
  {
    id: "guessMana",
    group: "games",
    route: "/guess-mana",
    iconSrc: "/ui/home-v2-icons/icon-mode-mana.png",
    accent: "blue",
    kind: "daily",
    es: {
      title: "Adivina el coste",
      description: "Elige su coste real de maná",
    },
    en: {
      title: "Guess the Cost",
      description: "Select its real mana cost",
    },
  },
  {
    id: "higherLower",
    group: "games",
    route: "/higher-lower",
    iconSrc: "/ui/home-v2-icons/icon-mode-higher-lower.png",
    accent: "emerald",
    kind: "daily",
    es: {
      title: "Mayor o menor",
      description: "Compara estadísticas entre cartas",
    },
    en: {
      title: "Higher or Lower",
      description: "Compare card stats in a streak",
    },
  },
  {
    id: "hiddenCard",
    group: "games",
    route: "/hidden-card",
    iconSrc: "/ui/home-v2-icons/icon-mode-hidden-card.png",
    accent: "violet",
    kind: "daily",
    es: {
      title: "La carta oculta",
      description: "Descúbrela con pistas progresivas",
    },
    en: {
      title: "The Hidden Card",
      description: "Find the card with clues",
    },
  },
  {
    id: "impostor",
    group: "games",
    route: "/impostor",
    iconSrc: "/ui/home-v2-icons/icon-mode-impostor.png",
    accent: "violet",
    kind: "daily",
    es: {
      title: "El Impostor",
      description: "Encuentra las buenas y evita la trampa",
    },
    en: {
      title: "The Impostor",
      description: "Find the good cards and avoid the trap",
    },
  },
  {
    id: "pyramid",
    group: "games",
    route: "/pyramid",
    iconSrc: "/ui/home-v2-icons/icon-mode-pyramid.png",
    accent: "blue",
    kind: "daily",
    es: {
      title: "Diez de Diez",
      description: "Adivina 10 cartas a contrarreloj",
    },
    en: {
      title: "Ten out of Ten",
      description: "Find 10 cards under a time limit",
    },
  },
  {
    id: "grid",
    group: "games",
    route: "/grid",
    iconSrc: "/ui/home-v2-icons/icon-mode-grid.png",
    accent: "gold",
    kind: "daily",
    es: {
      title: "Grid de cartas",
      description: "Completa el tablero de 3x3",
    },
    en: {
      title: "Card Grid",
      description: "Complete the 3x3 cell grid",
    },
  },
  {
    id: "cards",
    group: "library",
    route: "/cards",
    iconSrc: "/ui/home-v2-icons/icon-mode-database.png",
    accent: "emerald",
    kind: "available",
    es: {
      title: "Base de datos",
      description: "Filtra y consulta todas las cartas",
    },
    en: {
      title: "Card Database",
      description: "Browse and filter every card",
    },
  },
  {
    id: "collection",
    group: "library",
    route: "/collection",
    iconSrc: "/ui/home-v2-icons/icon-mode-collection.png",
    accent: "violet",
    kind: "available",
    es: {
      title: "Colección",
      description: "Abre sobres y completa tu álbum",
    },
    en: {
      title: "Collection",
      description: "Open chests and expand your collection",
    },
  },
  {
    id: "profile",
    group: "library",
    route: "/player",
    iconSrc: "/ui/home-v2-icons/icon-mode-profile.png",
    accent: "gold",
    kind: "available",
    es: {
      title: "Perfil",
      description: "Revisa tu progreso y estadísticas",
    },
    en: {
      title: "Profile",
      description: "Check your progress and records",
    },
  },
];
