const HIGHER_LOWER_COPY = {
  es: {
    resultKicker: "Resultado",
    dailyChallenge: "Reto diario",
    infiniteChallenge: "Modo infinito",
    scoreLabel: "Fases",
    streakLabel: "Racha",
    dailyRewardEarned: "Has ganado 1 caja arcana.",
    dailyRewardAlreadyClaimed: "Reto diario completado. Hoy ya tenías esta recompensa.",
    chooseLeft: "Elegir izquierda",
    chooseRight: "Elegir derecha",
    tieWin: "Empate: cuenta como acierto.",
    correct: "Correcto",
    wrong: "Fallaste",
    winTitle: "¡Racha completada!",
    winText: "Has acertado 10 duelos de cartas.",
    loseTitle: "Fin de la partida",
    loseText: "Has fallado un duelo de cartas.",
    viewResults: "Ver resultados",
    playAgain: "Otra partida",
    backHome: "Volver",
    noCards: "No hay suficientes cartas para crear duelos.",
    loading: "Preparando duelo...",
    resultsTitle: "Resultados",
    value: "valor",
    left: "Izquierda",
    right: "Derecha",
    tie: "Empate",
    selected: "Elegiste",
    correctSide: "Correcta",
    dailyReview: "Reto diario revisado",
  },
  en: {
    resultKicker: "Result",
    dailyChallenge: "Daily challenge",
    infiniteChallenge: "Infinite mode",
    scoreLabel: "Phases",
    streakLabel: "Streak",
    dailyRewardEarned: "You earned 1 arcane box.",
    dailyRewardAlreadyClaimed: "Daily challenge completed. You already had today’s reward.",
    chooseLeft: "Choose left",
    chooseRight: "Choose right",
    tieWin: "Tie: counts as correct.",
    correct: "Correct",
    wrong: "Wrong",
    winTitle: "Streak complete!",
    winText: "You got 10 card duels right.",
    loseTitle: "Game over",
    loseText: "You missed a card duel.",
    viewResults: "View results",
    playAgain: "Another game",
    backHome: "Back",
    noCards: "There are not enough cards to create duels.",
    loading: "Preparing duel...",
    resultsTitle: "Results",
    value: "value",
    left: "Left",
    right: "Right",
    tie: "Tie",
    selected: "Selected",
    correctSide: "Correct",
    dailyReview: "Daily review",
  },
};

export function getHigherLowerCopy(locale = "es") {
  return HIGHER_LOWER_COPY[locale] ?? HIGHER_LOWER_COPY.es;
}
