export const HIDDEN_CARD_COPY = {
  es: {
    resultKicker: "Resultado",
    dailyChallenge: "Reto diario",
    infiniteChallenge: "Modo infinito",
    attemptsLabel: "Intentos",
    guessesLabel: "Intentos usados",
    inputLabel: "Nombre de la carta",
    inputPlaceholder: "Escribe el nombre de la carta",
    submit: "Probar carta",
    noCards: "No hay suficientes cartas para jugar.",
    loading: "Preparando carta oculta...",
    correct: "¡Correcto!",
    wrong: "No era esa.",
    winTitle: "¡Carta descubierta!",
    winText: "Has identificado la carta oculta.",
    loseTitle: "Carta no descubierta",
    loseText: "Se han agotado los intentos.",
    viewResults: "Ver resultado",
    playAgain: "Otra carta",
    backHome: "Volver",
    dailyRewardEarned: "Has ganado 1 caja arcana.",
    dailyRewardAlreadyClaimed: "Reto diario completado. Hoy ya tenías esta recompensa.",
    hintTitle: "Pistas reveladas",
    hintImage: "Imagen oculta",
    hintCost: "Coste",
    hintType: "Tipo",
    hintClass: "Clase",
    hintRarity: "Rareza",
    hintName: "Nombre",
    hintText: "Texto",
    firstLetter: "empieza por",
    words: "palabras",
    selected: "Elegiste",
    emptyGuess: "Selecciona una carta de la lista o escribe un nombre exacto para probar.",
    invalidGuess: "Elige una carta válida de la lista antes de probar.",
  },
  en: {
    resultKicker: "Result",
    dailyChallenge: "Daily challenge",
    infiniteChallenge: "Infinite mode",
    attemptsLabel: "Attempts",
    guessesLabel: "Used attempts",
    inputLabel: "Card name",
    inputPlaceholder: "Type the card name",
    submit: "Try card",
    noCards: "There are not enough cards to play.",
    loading: "Preparing hidden card...",
    correct: "Correct!",
    wrong: "Not that card.",
    winTitle: "Card revealed!",
    winText: "You identified the hidden card.",
    loseTitle: "Card not found",
    loseText: "You ran out of attempts.",
    viewResults: "View result",
    playAgain: "Another card",
    backHome: "Back",
    dailyRewardEarned: "You earned 1 arcane box.",
    dailyRewardAlreadyClaimed: "Daily challenge completed. You already had today’s reward.",
    hintTitle: "Revealed clues",
    hintImage: "Hidden image",
    hintCost: "Cost",
    hintType: "Type",
    hintClass: "Class",
    hintRarity: "Rarity",
    hintName: "Name",
    hintText: "Text",
    firstLetter: "starts with",
    words: "words",
    selected: "Selected",
    emptyGuess: "Select a card from the list or type an exact card name before trying.",
    invalidGuess: "Choose a valid card from the list before trying.",
  },
};

export function getHiddenCardCopy(locale = "es") {
  return HIDDEN_CARD_COPY[locale] ?? HIDDEN_CARD_COPY.es;
}
