export const HOME_V2_COPY = {
  es: {
    navMinigames: "Minijuegos",
    navCards: "Base de datos",
    navCollection: "Colección",
    infoLabel: "Información",
    profileLabel: "Perfil",
    resetPrefix: "Nuevos retos en",
    loading: "Cargando cartas...",
    gamesTitle: "Minijuegos",
    libraryTitle: "Cartas y colección",
    play: "Jugar",
    open: "Abrir",
    soon: "Próximamente",
    daily: "Diario",
    available: "Disponible",
    packLabel: "Cajas",
    progressTitle: "Retos diarios",
    collectionProgress: "Colección",
    completedShort: "Hecho",
    pendingShort: "Pendiente",
    dailyGuessMana: "Coste",
    dailyImpostor: "Impostor",
    dailyGrid: "Grid",
    dailyPyramid: "Diez de Diez",
    dailyHigherLower: "Mayor o menor",
    dailyHiddenCard: "Carta oculta",
    dailyWon: "Completado",
    dailyLost: "Fallado",
    dailyPending: "Pendiente",
  },
  en: {
    navMinigames: "Minigames",
    navCards: "Card database",
    navCollection: "Collection",
    infoLabel: "Information",
    profileLabel: "Profile",
    resetPrefix: "New challenges in",
    loading: "Loading cards...",
    gamesTitle: "Minigames",
    libraryTitle: "Cards & collection",
    play: "Play",
    open: "Open",
    soon: "Coming soon",
    daily: "Daily",
    available: "Available",
    packLabel: "Boxes",
    progressTitle: "Daily challenges",
    collectionProgress: "Collection",
    completedShort: "Done",
    pendingShort: "Pending",
    dailyGuessMana: "Cost",
    dailyImpostor: "Impostor",
    dailyGrid: "Grid",
    dailyPyramid: "Ten out of Ten",
    dailyHigherLower: "Higher/lower",
    dailyHiddenCard: "Hidden card",
    dailyWon: "Completed",
    dailyLost: "Failed",
    dailyPending: "Pending",
  },
};

export const HOME_V2_MODES = [
  {
    id: "guessMana",
    group: "games",
    route: "/guess-mana",
    icon: "✦",
    iconSrc: "/ui/home-v2-icons/icon-mode-mana.png",
    accent: "blue",
    kind: "daily",
    es: {
      title: "Adivina el coste",
      description: "Observa la carta y elige su coste real.",
      cta: "play",
    },
    en: {
      title: "Guess the Cost",
      description: "Look at the card and choose its real mana cost.",
      cta: "play",
    },
  },
  {
    id: "higherLower",
    group: "games",
    route: "/higher-lower",
    icon: "↕",
    iconSrc: "/ui/home-v2-icons/icon-mode-higher-lower.png",
    accent: "emerald",
    kind: "daily",
    es: {
      title: "Mayor o menor",
      description: "Compara dos cartas y encadena aciertos.",
      cta: "play",
    },
    en: {
      title: "Higher or Lower",
      description: "Compare two cards and build a streak.",
      cta: "play",
    },
  },
  {
    id: "hiddenCard",
    group: "games",
    route: "/hidden-card",
    icon: "?",
    iconSrc: "/ui/home-v2-icons/icon-mode-hidden-card.png",
    accent: "violet",
    kind: "daily",
    es: {
      title: "La carta oculta",
      description: "Descubre una carta con pistas progresivas.",
      cta: "play",
    },
    en: {
      title: "The Hidden Card",
      description: "Reveal a card through progressive clues.",
      cta: "play",
    },
  },
  {
    id: "impostor",
    group: "games",
    route: "/impostor",
    icon: "◈",
    iconSrc: "/ui/home-v2-icons/icon-mode-impostor.png",
    accent: "violet",
    kind: "daily",
    es: {
      title: "Encuentra el impostor",
      description: "Detecta qué cartas encajan y evita la trampa.",
      cta: "play",
    },
    en: {
      title: "Find the Impostor",
      description: "Spot the cards that fit and avoid the trap.",
      cta: "play",
    },
  },
  {
    id: "pyramid",
    group: "games",
    route: "/pyramid",
    icon: "▲",
    iconSrc: "/ui/home-v2-icons/icon-mode-pyramid.png",
    accent: "blue",
    kind: "daily",
    es: {
      title: "Diez de Diez",
      description: "Encuentra diez cartas que encajen en la categoría.",
      cta: "play",
    },
    en: {
      title: "Ten out of Ten",
      description: "Find ten cards that match the category.",
      cta: "play",
    },
  },
  {
    id: "grid",
    group: "games",
    route: "/grid",
    icon: "▦",
    iconSrc: "/ui/home-v2-icons/icon-mode-grid.png",
    accent: "gold",
    kind: "daily",
    es: {
      title: "Grid de cartas",
      description: "Completa la cuadrícula con cartas que cumplan fila y columna.",
      cta: "play",
    },
    en: {
      title: "Card Grid",
      description: "Complete the grid with cards matching each row and column.",
      cta: "play",
    },
  },
  {
    id: "cards",
    group: "library",
    route: "/cards",
    icon: "⌕",
    iconSrc: "/ui/home-v2-icons/icon-mode-database.png",
    accent: "emerald",
    kind: "available",
    es: {
      title: "Base de datos",
      description: "Explora, filtra y consulta todas las cartas.",
      cta: "open",
    },
    en: {
      title: "Card Database",
      description: "Browse, filter, and inspect every card.",
      cta: "open",
    },
  },
  {
    id: "collection",
    group: "library",
    route: "/collection",
    icon: "⬡",
    iconSrc: "/ui/home-v2-icons/icon-mode-collection.png",
    accent: "violet",
    kind: "available",
    es: {
      title: "Colección",
      description: "Abre cajas arcanas y completa tu colección.",
      cta: "open",
    },
    en: {
      title: "Collection",
      description: "Open arcane boxes and complete your collection.",
      cta: "open",
    },
  },
  {
    id: "profile",
    group: "library",
    route: "/player",
    icon: "☰",
    iconSrc: "/ui/home-v2-icons/icon-mode-profile.png",
    accent: "gold",
    kind: "available",
    es: {
      title: "Perfil",
      description: "Consulta progreso, exporta datos o reinicia pruebas.",
      cta: "open",
    },
    en: {
      title: "Profile",
      description: "Check progress, export data, or reset tests.",
      cta: "open",
    },
  },
];
