export const HOME_V2_COPY = {
  es: {
    navMinigames: "Minijuegos",
    navCards: "Base de datos",
    navCollection: "Colección",
    infoLabel: "Información",
    resetPrefix: "Nuevos retos en",
    loading: "Cargando cartas...",
    gamesTitle: "Minijuegos",
    libraryTitle: "Cartas y colección",
    play: "Jugar",
    open: "Abrir",
    soon: "Próximamente",
    daily: "Diario",
    available: "Disponible",
    packLabel: "Sobres",
  },
  en: {
    navMinigames: "Minigames",
    navCards: "Card database",
    navCollection: "Collection",
    infoLabel: "Information",
    resetPrefix: "New challenges in",
    loading: "Loading cards...",
    gamesTitle: "Minigames",
    libraryTitle: "Cards & collection",
    play: "Play",
    open: "Open",
    soon: "Coming soon",
    daily: "Daily",
    available: "Available",
    packLabel: "Packs",
  },
};

export const HOME_V2_MODES = [
  {
    id: "guessMana",
    group: "games",
    route: "/guess-mana",
    icon: "✦",
    iconSrc: "/ui/home-v2-icons/icon-mode-mana.png",
    accent: "blue",
    kind: "daily",
    es: {
      title: "Adivina el coste",
      description: "Observa la carta y elige su coste real.",
      cta: "play",
    },
    en: {
      title: "Guess the Cost",
      description: "Look at the card and choose its real mana cost.",
      cta: "play",
    },
  },
  {
    id: "impostor",
    group: "games",
    route: "/impostor",
    icon: "◈",
    iconSrc: "/ui/home-v2-icons/icon-mode-impostor.png",
    accent: "violet",
    kind: "daily",
    es: {
      title: "Encuentra el impostor",
      description: "Detecta qué cartas encajan y evita la trampa.",
      cta: "play",
    },
    en: {
      title: "Find the Impostor",
      description: "Spot the cards that fit and avoid the trap.",
      cta: "play",
    },
  },
  {
    id: "grid",
    group: "games",
    route: "/grid",
    icon: "▦",
    iconSrc: "/ui/home-v2-icons/icon-mode-grid.png",
    accent: "gold",
    kind: "daily",
    es: {
      title: "Grid de cartas",
      description: "Completa la cuadrícula con cartas que cumplan fila y columna.",
      cta: "play",
    },
    en: {
      title: "Card Grid",
      description: "Complete the grid with cards matching each row and column.",
      cta: "play",
    },
  },
  {
    id: "cards",
    group: "library",
    route: "/cards",
    icon: "⌕",
    iconSrc: "/ui/home-v2-icons/icon-mode-database.png",
    accent: "emerald",
    kind: "available",
    es: {
      title: "Base de datos",
      description: "Explora, filtra y consulta todas las cartas.",
      cta: "open",
    },
    en: {
      title: "Card Database",
      description: "Browse, filter, and inspect every card.",
      cta: "open",
    },
  },
  {
    id: "collection",
    group: "library",
    route: null,
    icon: "⬡",
    iconSrc: "/ui/home-v2-icons/icon-featured-mission-star.png",
    accent: "muted",
    kind: "soon",
    es: {
      title: "Colección",
      description: "Guarda tus cartas y sigue tu progreso.",
      cta: "soon",
    },
    en: {
      title: "Collection",
      description: "Save your cards and track your progress.",
      cta: "soon",
    },
  },
];
