export const IMPOSTOR_COPY = {
  es: {
    resultKicker: "Resultado",
    dailyChallenge: "Reto diario",
    infiniteChallenge: "Modo infinito",
    dailyRewardEarned: "Has ganado 1 caja arcana.",
    dailyRewardAlreadyClaimed: "Reto diario completado. Hoy ya tenías esta recompensa.",
    category: "Categoría",
    objective: "Encuentra las cartas correctas y evita los impostores.",
    found: "{found} / {total} encontradas",
    foundLabel: "Cartas encontradas",
    selectPrompt: "Elige una carta",
    selectedPrompt: "Carta seleccionada",
    confirm: "Comprobar carta",
    noCards: "No hay cartas suficientes para crear una partida.",
    loading: "Preparando partida...",
    winTitle: "¡Perfecto!",
    winText: "Has encontrado todas las cartas correctas.",
    loseTitle: "Era un impostor",
    loseText: "La carta elegida no cumplía la categoría.",
    newGame: "Otra partida",
    backHome: "Volver",
    result: "Resultado",
    viewResults: "Ver resultados",
    playAgain: "Otra partida",
    allFound: "Has encontrado todas las cartas correctas.",
  },
  en: {
    resultKicker: "Result",
    dailyChallenge: "Daily challenge",
    infiniteChallenge: "Infinite mode",
    dailyRewardEarned: "You earned 1 arcane box.",
    dailyRewardAlreadyClaimed: "Daily challenge completed. You already had today’s reward.",
    category: "Category",
    objective: "Find the correct cards and avoid the impostors.",
    found: "{found} / {total} found",
    foundLabel: "Cards found",
    selectPrompt: "Choose a card",
    selectedPrompt: "Selected card",
    confirm: "Check card",
    noCards: "There are not enough cards to create a game.",
    loading: "Preparing game...",
    winTitle: "Perfect!",
    winText: "You found every correct card.",
    loseTitle: "That was an impostor",
    loseText: "The chosen card did not match the category.",
    newGame: "Another game",
    backHome: "Back",
    result: "Result",
    viewResults: "View results",
    playAgain: "Another game",
    allFound: "You found every correct card.",
  },
};

export function getImpostorCopy(locale) {
  return IMPOSTOR_COPY[locale] ?? IMPOSTOR_COPY.es;
}
