const GUESS_MANA_COPY = {
  es: {
    backHome: "Volver a minijuegos",
    resultKicker: "Resultado",
    dailyRewardEarned: "Has ganado 1 caja arcana.",
    dailyRewardAlreadyClaimed: "Reto diario completado. Hoy ya tenías esta recompensa.",
    dailyChallenge: "Reto diario",
    infiniteChallenge: "Modo infinito",
    chooseCost: "Elige un coste",
    selectedCost: "Coste seleccionado",
    confirmCost: "Confirmar coste",
    playAgain: "Otra carta",
    viewResults: "Ver resultados",
    correct: "¡Correcto!",
    wrong: "No era ese.",
    resultCostBefore: "cuesta",
    resultCostAfter: "de maná.",
    loadingGame: "Preparando carta...",
    noCards: "No hay cartas disponibles.",
    noImage: "Sin imagen",
  },
  en: {
    backHome: "Back to minigames",
    resultKicker: "Result",
    dailyRewardEarned: "You earned 1 arcane box.",
    dailyRewardAlreadyClaimed: "Daily challenge completed. You already had today’s reward.",
    dailyChallenge: "Daily challenge",
    infiniteChallenge: "Infinite mode",
    chooseCost: "Choose a cost",
    selectedCost: "Selected cost",
    confirmCost: "Confirm cost",
    playAgain: "Another card",
    viewResults: "View results",
    correct: "Correct!",
    wrong: "Not that one.",
    resultCostBefore: "costs",
    resultCostAfter: "mana.",
    loadingGame: "Preparing card...",
    noCards: "No cards available.",
    noImage: "No image",
  },
};

export function getGuessManaCopy(locale) {
  return GUESS_MANA_COPY[locale] ?? GUESS_MANA_COPY.es;
}
